### ISSUE TITLE
Circular interpolation arcs end early

### ISSUE THREAD

**Issue by slindberg** [nraynaud/webgcode#10]
Thanks for the awesome tool, I'm using it to proof my G-code before trying it on a real CNC. I don't know if I'm missing something, but it appears that circular interpolation endpoints aren't completed properly when followed by a G0 or a G1. I think it's easiest to just show you [an example](https://gist.github.com/slindberg/c95765b1d42619cdb77d97610dc7d8c3). Pasting that code into the simulator, you can see that arcs in the XY plane terminate early, and the G0 to the clearance plane (Z0.25) is diagonal instead of vertical. This happens on the bottom of the eyes as well, when a G2 is followed by a G1.

**Comment by nraynaud** [comment]
Thanks for the report with the nice repro, that looks buggy to me too.

**Comment by nraynaud** [comment]
wait, I didn't mean to close it.

**Comment by nraynaud** [comment]
Can you check that I fixed it please?

**Comment by slindberg** [comment]
Looks like that did it! Thanks again for the great tool.
