### ISSUE TITLE
G02 with only Y parameter locks up webgcode

### ISSUE THREAD

**Issue by dafzor** [nraynaud/webgcode#13]
When writing the code `G02 Y20` simulating it will lock webgcode tool in a permanent simulation cycle.

**Comment by nraynaud** [comment]
Thanks for your report, 
I confirm I can reproduce this behavior, let me have a closer look.

**Comment by nraynaud** [comment]
Upon further inspection, I don't think that code is legal, because there is no way to compute the arc path without either a center or a radius, I'll just detect and report the error.

**Comment by nraynaud** [comment]
Ok, I detected and reported the error. 
If you think I misunderstood either your bug report or how the G2 command is supposed to work, please re-open with your comments.

**Comment by dafzor** [comment]
The issue is indeed that inputing the code in that manner soft locks the webgcode app into a simulation loop instead of simply trowing an error, thus forcing a reload to continue using it.

I'm currently learning gcode and using your web app on my phone to validate my exercises gcode, thus the higher probability of bad code inputs.

Your fix is perfect, thanks

**Comment by nraynaud** [comment]
ok, it's fixed for this instance.
But expect a lot more issues of the same type, I did almost no verification of the input.

**Comment by dafzor** [comment]
I'll report them as I find them if you don't mind.

**Comment by nraynaud** [comment]
Yes, thank you, that will increase the general quality.
