### ISSUE TITLE
webgcode app doesn't seem to recognise valid G41, G42 gcode

### ISSUE THREAD

**Issue by dafzor** [nraynaud/webgcode#15]
When using the instruction `G42 D1` the webgcode app seems to not recognize the command. This however should be valid gcode (at least it seems to function as expected in the CNC machine I'm learning with).

Note however that everything still seems to function well so it's just a "minor" bug.

**Comment by nraynaud** [comment]
Yes, I didn't implement it. 
Tool radius compensation is a tricky subject, some machines will move on the side as soon as you set it and other will start moving sideways on the first move after a tool radius definition. Since I had no real target in mind, I didn't bother implementing it.

**Comment by dafzor** [comment]
Would it be possible to change the error message to something like "G42, Not implemented, skipping" or similar error message to make it clearer that it's not a user error?

**Comment by nraynaud** [comment]
ok, done.
