### ISSUE TITLE
using webgcode

### ISSUE THREAD

**Issue by tomas-westrin** [nraynaud/webgcode#20]
Hi
You did wrote that this is the contact space when someone needed to contact you.
I use your code on my CNC website, its it freaking awesome programming you did there.
As I interpret it, this software is free to use. (?)
Did some beating on it, but the major deal it's your code.
I'v putted it on http://www.tomasw.com/gcodesim.
and again, really good job :)

/tomas

**Comment by nraynaud** [comment]
I am glad you find it useful.
Thanks for telling me.
