### ISSUE TITLE
Add toolchange options

### ISSUE THREAD

**Issue by thboomsma** [nraynaud/webgcode#33]
First of all .. great tool especially for a smal lab that has many processes on minimal amount of flexible machines.

As a feature request i would suggest adding the tool-chance as an option on each of the processing steps. If not selected default tool prevails.

Is this gcode GRBL compatible? We standarddized all machines to that for simplicity.
How is the STM compared to Arduino boards?

Thank you!
Theo

**Comment by nraynaud** [comment]
Hi, sorry but this project is not really active anymore.

The code is probably not compatible with GRBL, because I made no effort to be compatible with it.

I think the STM32F407 has more resources, but I'm not really sure, I just chose it because that's what I had.
