### ISSUE TITLE
Fails with '%' in comment

### ISSUE THREAD

**Issue by jackbrennan-creator** [nraynaud/webgcode#41]
Fails with '%' in comment.

Example: 
`G1 Y14 S1000 F60 ; Move 04,14 laser 100%, speed 1mm/sec`

Looks like it terminates the program?

**Comment by nraynaud** [comment]
Thank you very much for your report, I believe it's fixed it here now : https://github.com/nraynaud/webgcode/commit/5c4e828d3289a3ca8aaff63123a7695f5a38d680
