### ISSUE TITLE
WebGcode simulator

### ISSUE THREAD

**Issue by pauljay** [nraynaud/webgcode#5]
Hi,
I have tried out webgcode simulator. But I can't paste my gcode onto the left window since there is no left window to put the gcode.

How can I make it show the left window to put my g code ?

I am making my own CNC board. My firmware is in between GRBL and Smoothie also something like a mashup of them. Though I have a g code viewer on Windows OS, I need to make a some G code community site where popular milling operations G code are exchanged like Thingiverse.

Regards,

Paul J

**Comment by nraynaud** [comment]
Hi Paul,
I'm sorry an SVG API has been removed from Chrome, and you are right, it broke the left hand side panel. I'll try to fix it soon. In the mean time, you can try with firefox.

Thanks for trying my software.

Nicolas.

**Comment by pauljay** [comment]
Thank you for your reply.

2016년 6월 29일 수요일, Nicolas Raynaudnotifications@github.com님이 작성한 메시지:

**Comment by nraynaud** [comment]
Hello Paul, that seems to be fixed, albeit the thing is now quite slow.

**Comment by pauljay** [comment]
Yes, it works now on Chrome albeit it's some slow to load.
However, it works very flawlessly on FireFox.
Do you use WebGL on FireFox ?

**Comment by nraynaud** [comment]
I use webgl on both of them. It's the SVG system that as now become slow on Chrome, since they removed a native API, it is simulated in javascript.
