### ISSUE TITLE
Fork for Vanity (:

### ISSUE THREAD

**Issue by ghost** [nraynaud/webgcode#7]
Hey.

You have quite an interesting project, and VisualCam in particular is interesting.

Would you be willing to give me an open source fork to work from? 
I am in particular interested in extending your dragknife support, and more 3D milling. 

We also use a threejs+clipperjs backend on Laserweb

Laserweb has quite a bit of traffic - which could help bring some fame.  (We even have a sponsors WIKI page that has managed to nett some of the contributors machines, boards and paypal donations - i'd be happy to put your details on there if we use some of your code. )

**Comment by nraynaud** [comment]
yeah, sure! what licence do you want?
Would MIT do it for you?
I guess it's time for me to _really_ open source this stuff.

**Comment by ghost** [comment]
(: I honestly an stuck in the same boat you are - licences are sooo tough to choose. 

I have LaserWeb as GNU Affero General Public License - but there are sections of the code from contributors, forks and libraries which means its not fully GPL at all. 
My argument is I'm happy to maintain a more restrictive licence on a component inside the project, if thats the original authors wish.  Ultimately I believe credit, honor and trust come above all. 

Thats why I like sticking credits and "Author: XXX" into headers and comments so often  (:

At the end of the day - the more people see your code right (;

**Comment by nraynaud** [comment]
Here we go, double license, MIT + Affero GPL.

**Comment by ghost** [comment]
Thanks (: ! (;  

Your functions: 
![dragknife](https://cloud.githubusercontent.com/assets/7695323/16925308/e0cb1cf2-4d23-11e6-9106-5f7a74221c17.PNG) 

much better than what we had as work in progress ( https://github.com/openhardwarecoza/LaserWeb2/commits/DragKnife )

**Comment by ghost** [comment]
(: Do you have a Google+ account so I can tag you properly?

**Comment by nraynaud** [comment]
I do have a google+ account, but I have no idea of the URL. maybe that: https://plus.google.com/u/0/103823220772217784777/ ?

**Comment by nraynaud** [comment]
After thinking for about it for a bit, I think the picture has a problem, I might have made a bug.

**Comment by ghost** [comment]
Or my porting of your code may have a bug.  Transplanted just the dragknife
code into my existing code

**Comment by ghost** [comment]
https://github.com/openhardwarecoza/LaserWeb3/commit/48cac8f5d65f41013f497052516153f70230da3b
