### ISSUE TITLE
CAM dev resources 

### ISSUE THREAD

**Issue by Dcarter10177** [nraynaud/webgcode#8]
Cool Project. I was wondering what resources (research papers, books, blogs etc...) you used to start developing your own CAM software. I am interested in creating my own toolpath and any insight to your learning process would be much appreciated. Thanks.

**Comment by nraynaud** [comment]
I read the ideas of Martin Held, but I never implemented anything fancy in the end. I also received a stack of research papers on the subject by a generous academic, but again, I didn't implement any smart ideas. 
It's mostly taking the JSClipper code and using it in a basic manner.

**Comment by Dcarter10177** [comment]
Thank you for the information. The work of Martin Held looks very interesting. Thanks Again.
